server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_exercise?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mypassword
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  mapperLocations: classpath:mappers/*.xml
  type-aliases-package: com.mcg.exercise.entity

operate:
  scanPackage: test
  operateName: test